// List of accounts to track
export const TRACKED_ACCOUNTS = [
    '0xMert_',
    'blknoiz06',
    'DeeZe',
    'Loopifyyy',
    '0xMerp',
    'optimizoor',
    'DancingEddie_',
    'VitalikButerin',
    'notthreadguy',
    'aeyakovenko',
    'rajgokal',
    'zhusu',
    'vydamo_',
    'zachxbt',
    'metaversejoji',
    'casino616',
    'ShockedJS',
    'BastilleBtc',
    'spunosounds',
    'TheMisterFrog',
    '0xGroovy',
    '973Meech',
    'rektober',
    'frankdegods',
    'orangie',
    'imperooterxbt',
    'sabby_eth',
    'NokiTheTrader',
    'moneymaykah_',
    'rasmr_eth',
    'MustStopMurad',
    'staccoverflow',
    'mememe69696969',
    'dolonosolo',
    // 'based16z'
];